# Generated by Django 2.2.7 on 2020-03-30 14:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.GenericIPAddressField(null=True, verbose_name='连接主机')),
                ('user', models.CharField(max_length=64, null=True, verbose_name='使用用户')),
                ('ssh_user', models.CharField(blank=True, max_length=128, null=True, verbose_name='ssh用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('end_time', models.DateTimeField(auto_now=True, null=True, verbose_name='结束时间')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, '已结束'), (1, '正在进行')], default=1, null=True, verbose_name='状态')),
                ('used', models.BooleanField(default=False, null=True, verbose_name='是否连接过')),
                ('link_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP')),
            ],
            options={
                'verbose_name': '会话连接记录表',
                'verbose_name_plural': '会话连接记录表',
                'db_table': 'ssh_session_log',
                'permissions': (('run_webssh', '是否能执行远程主机'),),
            },
        ),
        migrations.CreateModel(
            name='CodeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('command', models.TextField()),
                ('result', models.TextField(null=True)),
                ('connection', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='log', to='webssh.SessionLog')),
            ],
            options={
                'db_table': 'code_log',
            },
        ),
    ]
