# Generated by Django 2.2.7 on 2020-03-25 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, unique=True, verbose_name='IP')),
                ('status', models.PositiveIntegerField(choices=[(0, '下线'), (1, '在线'), (2, '故障中'), (3, '未使用'), (4, '未知')], default=1, verbose_name='设备状态')),
                ('asset_type', models.PositiveIntegerField(choices=[(1, '物理机'), (2, '虚拟机'), (3, '云主机')], verbose_name='资产类型')),
                ('system', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作系统')),
                ('is_del', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否删除')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='激活')),
                ('is_pass', models.BooleanField(blank=True, default=True, null=True, verbose_name='可连接')),
                ('sshuser', models.CharField(blank=True, max_length=64, null=True, verbose_name='SSH用户')),
                ('sshport', models.CharField(blank=True, default=22, max_length=5, null=True, verbose_name='SSH端口')),
                ('sshpwd', models.CharField(blank=True, max_length=128, null=True, verbose_name='SSH密码')),
                ('ftp_port', models.CharField(blank=True, max_length=5, null=True, verbose_name='FTP端口')),
                ('cpu', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU型号')),
                ('logical_cpu', models.PositiveIntegerField(blank=True, null=True, verbose_name='逻辑CPU数')),
                ('ram', models.IntegerField(blank=True, null=True, verbose_name='内存容量')),
                ('disk', models.FloatField(blank=True, null=True, verbose_name='磁盘容量')),
                ('remark', models.TextField(verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产表',
                'verbose_name_plural': '资产表',
                'db_table': 'assets',
                'permissions': (('asset_export', '能否导出资产表'), ('asset_import', '能否导入资产表')),
            },
        ),
        migrations.CreateModel(
            name='DelAssetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('asset_type', models.PositiveIntegerField(blank=True, choices=[(1, '物理机'), (2, '虚拟机'), (3, '云主机')], null=True, verbose_name='资产类型')),
                ('sshuser', models.CharField(blank=True, max_length=64, null=True, verbose_name='SSH用户')),
                ('sshpwd', models.CharField(blank=True, max_length=128, null=True, verbose_name='SSH密码')),
                ('cpu', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU型号')),
                ('logical_cpu', models.PositiveIntegerField(blank=True, null=True, verbose_name='逻辑CPU数')),
                ('delete_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '资产删除登记表',
                'verbose_name_plural': '资产删除登记表',
                'db_table': 'assets_del',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='机房名称')),
                ('linkphone', models.CharField(blank=True, max_length=16, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='机房地址')),
                ('network_segment', models.TextField(blank=True, null=True, verbose_name='网段')),
                ('bandwidth', models.CharField(blank=True, max_length=64, null=True, verbose_name='机房带宽')),
                ('operator', models.PositiveIntegerField(blank=True, choices=[(0, '电信'), (1, '联通'), (2, '移动'), (3, '铁通'), (4, '小带宽')], null=True, verbose_name='运营商')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'IDC资产表',
                'verbose_name_plural': 'IDC资产表',
                'db_table': 'idc',
            },
        ),
        migrations.CreateModel(
            name='PushSystemUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='推送用户')),
                ('host', models.GenericIPAddressField(verbose_name='推送主机')),
                ('push_time', models.DateTimeField(auto_now_add=True, verbose_name='推送时间')),
            ],
            options={
                'verbose_name': '系统用户推送表',
                'verbose_name_plural': '系统用户推送表',
                'db_table': 'push_user_log',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='登录用户名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='登录密码')),
                ('group', models.CharField(blank=True, max_length=128, null=True, verbose_name='组')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
                'db_table': 'system_user',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='标签')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资产标签表',
                'verbose_name_plural': '资产标签表',
                'db_table': 'tags',
            },
        ),
    ]
