# Generated by Django 2.2.7 on 2020-03-25 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='pushsystemuserlog',
            name='pusher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='推送者'),
        ),
        migrations.AddField(
            model_name='assets',
            name='creator',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets',
            name='idc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.IDC', verbose_name='所属机房'),
        ),
        migrations.AddField(
            model_name='assets',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='assets',
            name='system_users',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='assets', to='assets.SystemUser', verbose_name='系统用户'),
        ),
        migrations.AddField(
            model_name='assets',
            name='tags',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='assets.Tags', verbose_name='标签'),
        ),
    ]
