# Generated by Django 2.2.7 on 2020-03-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loginlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_created=True, verbose_name='登录时间')),
                ('user', models.CharField(max_length=128, verbose_name='用户名')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='登录IP')),
                ('status', models.BooleanField(choices=[(0, '失败'), (1, '成功')], verbose_name='登录状态')),
            ],
            options={
                'verbose_name': '登录日志',
                'db_table': 'login_log',
            },
        ),
        migrations.CreateModel(
            name='OperatingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('user', models.CharField(editable=False, max_length=128, verbose_name='操作用户')),
                ('action', models.CharField(choices=[('add', '增加'), ('view', '查看'), ('change', '修改'), ('del', '删除')], editable=False, max_length=32, verbose_name='动作')),
                ('resource', models.CharField(editable=False, max_length=32, verbose_name='资源类型')),
                ('operating', models.CharField(editable=False, max_length=256, verbose_name='执行操作')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='远端地址')),
            ],
            options={
                'verbose_name': '操作日志',
                'db_table': 'operating_log',
            },
        ),
    ]
