# Generated by Django 2.2.7 on 2020-03-25 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auth_users',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='授权用户'),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
